sudo: false

language: python

python:
  - 3.3
  - 3.4

addons:
  apt:
    packages:
      - texlive-xetex
      - texlive-latex-recommended
      - lmodern
      - texlive-latex-extra
      - texlive-lang-greek
      - fonts-linuxlibertine
      - poppler-utils

install:
  - pip install flake8
  - pip install -r requirements.txt
  - mkdir ci.deps
  - curl -o ci.deps/lexemes.yaml https://raw.githubusercontent.com/morphgnt/morphological-lexicon/4e3dbfd872bc12d11d8949be98e4f72dfc0ea9f0/lexemes.yaml

before_script:
  - describe_pdf_file() { pdftotext "${1:?}" -; } # http://stackoverflow.com/questions/6187250/pdf-text-extraction/6189489#6189489
  - build_reader_LaTeX() { local D="${1:?}"; local T="${2:?}.tex"; cat - > "${D}/$T"; cd "$D"; xelatex "$T" && xelatex "$T" || exit 1; }
  - reader_filename_LaTeX() { echo "${1:?}.pdf"; }
  - describe_reader_file_LaTeX() { describe_pdf_file "${1:?}"; }
  - build_reader_SILE() { local D="${1:?}"; local T="${2:?}.sil"; cat - > "${D}/$T"; cd "$D"; sile "$T" || exit 1; }
  - reader_filename_SILE() { echo "${1:?}.pdf"; }
  - describe_reader_file_SILE() { describe_pdf_file "${1:?}"; }
  - flake8 .
  - fc-list
  - mkdir ci.out

script:
  - ./frequency_exclusion.py 31 > ci.out/exclude.txt
  - echo "μήν" >> ci.out/exclude.txt # `μήν/N` (noun, strong 3376, gloss "a month") or `μήν/X` (particle, strong 3375, gloss "certainly")? Ref https://github.com/morphgnt/morphological-lexicon/commit/0c96a74f08381933f1de21457cc7d13f1aa5654e#diff-2d41209e747bb484493248c8f3f2158f
  - ./make_glosses.py --exclude ci.out/exclude.txt --lexicon ci.deps/lexemes.yaml "$VERSES" > ci.out/glosses.yaml
  - ./make_headwords.py --exclude ci.out/exclude.txt --lexicon ci.deps/lexemes.yaml "$VERSES" > ci.out/headwords.yaml
  - ./reader.py --headwords ci.out/headwords.yaml --glosses ci.out/glosses.yaml --language eng --exclude ci.out/exclude.txt --typeface "Linux Libertine O" "$VERSES" --backend backends.$BACKEND | build_reader_$BACKEND ci.out reader
  - RF=$(reader_filename_$BACKEND reader)
  - ls -l ci.out/$RF

after_success:
  - file ci.out/$RF
  - describe_reader_file_$BACKEND ci.out/$RF

env:
  - BACKEND=LaTeX VERSES="John 18:1-11"
  - BACKEND=SILE VERSES="John 18:1-11"
  - BACKEND=LaTeX VERSES="Matthew 1:1-Revelation 22:21"

matrix:
  allow_failures:
    - env: BACKEND=SILE VERSES="John 18:1-11"
    - env: BACKEND=LaTeX VERSES="Matthew 1:1-Revelation 22:21"
  fast_finish: true
