sudo: false

language: python

python:
  - 3.3
  - 3.4

addons:
  apt:
    packages:
      - texlive-xetex
      - texlive-latex-recommended
      - lmodern
      - texlive-latex-extra
      - texlive-lang-greek
      - fonts-linuxlibertine
      - poppler-utils

install:
  - ./ci install

before_script:
  - fc-list
  - ./ci before_script

script:
  - ./ci script $BACKEND "$VERSES" $LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE

after_success:
  - ./ci after_success $BACKEND

env:
  - BACKEND=LaTeX VERSES="John 18:1-11" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=31
  - BACKEND=LaTeX VERSES="John 18:1-11" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=48
  - BACKEND=LaTeX VERSES="John 18:1-11" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=662
  - BACKEND=LaTeX VERSES="John 18:1-11" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=1000000
  - BACKEND=SILE VERSES="John 18:1-11" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=31
  - BACKEND=MySword VERSES="John 18:1-11" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=31
  - BACKEND=MySword VERSES="John 18:1-11" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=1000000
  - BACKEND=LaTeX VERSES="Matthew 1:1-Revelation 22:21" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=31
  - BACKEND=LaTeX VERSES="Matthew 1:1-Revelation 22:21" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=48
  - BACKEND=LaTeX VERSES="Matthew 1:1-Revelation 22:21" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=190
  - BACKEND=MySword VERSES="Matthew 1:1-Revelation 22:21" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=1000000

matrix:
  allow_failures:
    - env: BACKEND=SILE VERSES="John 18:1-11" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=31
    - env: BACKEND=LaTeX VERSES="Matthew 1:1-Revelation 22:21" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=31
    - env: BACKEND=LaTeX VERSES="Matthew 1:1-Revelation 22:21" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=48
    - env: BACKEND=LaTeX VERSES="Matthew 1:1-Revelation 22:21" LOWER_OCCURRENCE_LIMIT_TO_EXCLUDE=190
  fast_finish: true
